---
---
= DevoxxFR 2015

Cette année, j'ai eu la chance d'aller à http://devoxx.fr/[Devoxx France] au Palais des Congrès à Paris. Et je tiens tous de suite à remercier http://salto-consulting.com/[Salto Consulting] pour qui je travaille et http://www.oxiane.com/[Oxiane] l'organisme de formation, pour m'avoir permis d'y aller. En résumé c'était génial, à tel point que j'ai enfin décidé de créer mon blog pour partager cette expérience.

Que dire... le plein d'émotions. Vraiment, se retrouver au milieu de millier de geeks, des discutions intéressantes dans tous les coins. Croiser plein de "stars" du monde java au même endroit. C'est juste bluffant.

Avant de venir, j'imaginais une sorte de JUG mais sur trois jours. En fait c'est bien plus que ça. Non seulement il faut choisir entre pléthore de sujets intéressants, mais en plus ça va à toute vitesse ! à peine une conférence terminée, la tête pleine d'idée et hop on fait le tour du palais et on repart sur un autre sujet tout aussi intéressant !

Les organisateurs parlent de Devoxx Blues. Qu'ils ne se sentent pas seul, cette une étrange sensation que de revenir au monde réel. Et pour autant c'est justement là tous le plaisir : revenir au boulot des idées plein la tête et faire avancer le monde !

Si je devais retenir quelques moments forts ça commencerait par les keynotes. Se projeter dans l’avenir, mettre notre travail en perspective, penser aux conséquences... Un véritable moment de réflexion. En théorie on dit aujourd'hui que le logiciel envahit le monde (software is eating the world), en pratique, tous les jours au travail : c'est juste vrai. Est-ce qu'un bug en prod pénalise un utilisateur ? Est-ce qu'une faille de sécurité peut engendrer une fuite d'informations confidentielles pour votre entreprise|employeur|client ? N'ai-je pas le sourire quand après de nombreux efforts une nouvelle fonctionnalité part en production et rend service à plein de monde ?

Un autre moment "awesome" également : rencontrer des commiteurs maven au BoF, discuter avec eux, comprendre la problématique du projet que vous utilisez tous les jours. Et s'enrichir de ses échanges pour mieux comprendre les enjeux et ce que l'on peut faire. (par exemple en essayant de contribuer !)

Et enfin juste Devoxx. Des démos impressionnantes, des hands'lab pour mettre les mains dans le cambouis et des idées plein la tête. J'avais déjà aimé l'expérience de l'Agile Tour pour l'ouverture d'esprit que cela peut apporter. Là on y retrouve les mêmes ingrédients avec plus d'effervescence encore.

Si un jour je me décide à changer le monde. ça sera certainement un lendemain de Devoxx !
